# Generated by Django 3.1.13 on 2023-08-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(choices=[('Gadgets', 'Gadgets'), ('Drones', 'Drones'), ('Batteries', 'Batteries'), ('Panels', 'Panels'), ('Home Appliances', 'Home Appliances'), ('Electric Autos', 'Electric Autos')], max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
