# Generated by Django 3.1.13 on 2023-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='Company_Name',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_port',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
