# Generated by Django 3.1.13 on 2023-08-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20230814_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='user',
        ),
    ]
