# Generated by Django 3.1.13 on 2023-08-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20230814_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=None, editable=False, unique=True),
        ),
    ]
